export const actionReceiveOrder = {
  ADD_RECEIVE_ORDER: "ADD_RECEIVE_ORDER" as const,
  ADD_RECEIVE_ORDER_SUCCESS: "ADD_RECEIVE_ORDER_SUCCESS" as const,
  ADD_RECEIVE_ORDER_ERROR: "ADD_RECEIVE_ORDER_ERROR" as const,
  LOAD_RECEIVE_ORDER_REQUEST: "LOAD_RECEIVE_ORDER_REQUEST" as const,
  LOAD_RECEIVE_ORDER_SUCCESS: "LOAD_RECEIVE_ORDER_SUCCESS" as const,
  LOAD_RECEIVE_ORDER_ERROR: "LOAD_RECEIVE_ORDER_ERROR" as const,
  UPDATE_RECEIVE_ORDER: "UPDATE_RECEIVE_ORDER" as const,
  UPDATE_RECEIVE_ORDER_SUCCESS: "UPDATE_RECEIVE_ORDER_SUCCESS" as const,
  UPDATE_RECEIVE_ORDER_ERROR: "UPDATE_RECEIVE_ORDER_ERROR" as const,
  LOAD_ALL_RECEIVE_ORDER: "LOAD_ALL_RECEIVE_ORDER" as const,
  LOAD_ALL_RECEIVE_ORDER_SUCCESS: "LOAD_ALL_RECEIVE_ORDER_SUCCESS" as const,
  LOAD_ALL_RECEIVE_ORDER_ERROR: "LOAD_ALL_RECEIVE_ORDER_ERROR" as const,
  LOAD_ALL_ORDER_SUPPLIER: "LOAD_ALL_ORDER_SUPPLIER" as const,
  LOAD_ALL_ORDER_SUPPLIER_SUCCESS: "LOAD_ALL_ORDER_SUPPLIER_SUCCESS" as const,
  LOAD_ALL_ORDER_SUPPLIER_ERROR: "LOAD_ALL_ORDER_SUPPLIER_ERROR" as const,
};
type ActionReceiveOrder =
  (typeof actionReceiveOrder)[keyof typeof actionReceiveOrder];
export type { ActionReceiveOrder };
